version: "3.9"

services:
  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth-service"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    restart: always

  postgres-posts:
    image: postgres:15
    container_name: postgres-posts
    environment:
      POSTGRES_DB: ${POSTS_DB_NAME}
      POSTGRES_USER: ${POSTS_DB_USER}
      POSTGRES_PASSWORD: ${POSTS_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d posts-service"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5434:5432"
    restart: always

  auth-service:
    build:
      context: ./backend/auth-service
    container_name: auth-service
    environment:
      AUTH_DB_HOST: ${AUTH_DB_HOST}
      AUTH_DB_NAME: ${AUTH_DB_NAME}
      AUTH_DB_USER: ${AUTH_DB_USER}
      AUTH_DB_PASSWORD: ${AUTH_DB_PASSWORD}
      AUTH_SERVICE_PORT: ${AUTH_SERVICE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      AUTH_DB_PORT: ${AUTH_DB_PORT}
    ports:
      - "4001:4001"
    restart: always
    depends_on:
      postgres-auth:
        condition: service_healthy

  posts-service:
    build:
      context: ./backend/posts-service
    container_name: posts-service
    environment:
      POSTS_DB_HOST: ${POSTS_DB_HOST}
      POSTS_DB_NAME: ${POSTS_DB_NAME}
      POSTS_DB_USER: ${POSTS_DB_USER}
      POSTS_DB_PASSWORD: ${POSTS_DB_PASSWORD}
      POSTS_SERVICE_PORT: ${POSTS_SERVICE_PORT}
      POSTS_DB_PORT: ${POSTS_DB_PORT}
    ports:
      - "4002:4002"
    restart: always
    depends_on:
      postgres-auth:
        condition: service_healthy
