version: "3.9"

services:
  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_DB_USER} -d ${AUTH_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    restart: always

  postgres-posts:
    image: postgres:15
    container_name: postgres-posts
    environment:
      POSTGRES_DB: ${POSTS_DB_NAME}
      POSTGRES_USER: ${POSTS_DB_USER}
      POSTGRES_PASSWORD: ${POSTS_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTS_DB_USER} -d ${POSTS_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5434:5432"
    restart: always

  auth-service:
    build:
      context: ./backend/auth-service
    container_name: auth-service
    env_file:
      PORT: ${AUTH_SERVICE_PORT}
      DB_HOST: postgres-auth
      DB_PORT: 5432
      DB_NAME: ${AUTH_DB_NAME}
      DB_USER: ${AUTH_DB_USER}
      DB_PASSWORD: ${AUTH_DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    restart: always
    depends_on:
      postgres-auth:
        condition: service_healthy

  posts-service:
    build:
      context: ./backend/posts-service
    container_name: posts-service
    env_file:
      PORT: ${POSTS_SERVICE_PORT}
      DB_HOST: postgres-posts
      DB_PORT: 5432
      DB_NAME: ${POSTS_DB_NAME}
      DB_USER: ${POSTS_DB_USER}
      DB_PASSWORD: ${POSTS_DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${POSTS_SERVICE_PORT}:${POSTS_SERVICE_PORT}"
    restart: always
    depends_on:
      postgres-auth:
        condition: service_healthy
